apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.linuxdays.sikademo.com
  admin.enabled: "true"
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "false"
  oidc.config: |
    name: SSO
    issuer: https://sso.linuxdays.sikademo.com/realms/linuxdays
    clientID: argocd
    clientSecret: argocd_secret
    requestedScopes: ["openid", "profile", "email", "groups"]
    logoutURL: "https://sso.linuxdays.sikademo.com/realms/sikademo/protocol/openid-connect/logout?client_id=argocd&id_token_hint={{token}}&post_logout_redirect_uri=https://argocd.linuxdays.sikademo.com"
  oidc.tls.insecure.skip.verify: "true"
  server.rbac.log.enforce.enable: "false"
  timeout.hard.reconciliation: 0s
  timeout.reconciliation: 180s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    g, argocd-admin, role:admin
    g, argocd-readonly, role:readonly
  policy.default: ""
  scopes: '[groups]'
