apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 6.60.1
    helm:
      releaseName: grafana
      values: |
        adminPassword: admin
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - grafana.linuxdays.sikademo.com
          tls:
            - hosts:
                - grafana.linuxdays.sikademo.com
              secretName: grafana-tls
        grafana.ini:
          server:
            root_url: https://grafana.linuxdays.sikademo.com
          auth.basic:
            enabled: true
          auth:
            disable_login_form: false
          auth.generic_oauth:
            enabled: true
            name: Keycloak SSO
            allow_sign_up: true
            scopes: "openid profile email"
            auth_url: https://sso.linuxdays.sikademo.com/realms/linuxdays/protocol/openid-connect/auth
            token_url: https://sso.linuxdays.sikademo.com/realms/linuxdays/protocol/openid-connect/token
            api_url: https://sso.linuxdays.sikademo.com/realms/linuxdays/protocol/openid-connect/userinfo
            client_id: grafana
            client_secret: "grafana_secret"
            role_attribute_path: contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-viewer') && 'Viewer'
